<?php

namespace Database\Seeders;

use App\Models\Diagnostico;
use Illuminate\Database\Seeder;

class DiagnosticosSeeder extends Seeder
{
    public function run()
    {
        $diagnosticos = [
            ['codigo' => '1', 'patologia' => 'FIEBRE TIFOIDEA Y PARATIFOIDEA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '2', 'patologia' => 'DISENTERIA BACILAR', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '3', 'patologia' => 'DISENTERIA AMEBIANA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '4', 'patologia' => 'DIARREAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '5', 'patologia' => 'TUBERCULOSIS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '6', 'patologia' => 'HEPATITIS INFECCIOSA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '7', 'patologia' => 'DIFTERIA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '8', 'patologia' => 'TOSFERINA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '9', 'patologia' => 'INFECCION MENINGOCOCICA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '10', 'patologia' => 'TETANO NEONATORUM', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '11', 'patologia' => 'POLIOMIELITIS AGUDA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '12', 'patologia' => 'SARAMPION', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '13', 'patologia' => 'RUBEOLA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '15', 'patologia' => 'SOSPECHA DE ZIKA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '16', 'patologia' => 'CHIKUNGUNYA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '17', 'patologia' => 'LUMBALGIA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '18', 'patologia' => 'HEMORROIDES', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '19', 'patologia' => 'MALARIA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '20', 'patologia' => 'LEISHMANIASIS CUTANEA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '21', 'patologia' => 'SIFILIS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '22', 'patologia' => 'GONORREA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '23', 'patologia' => 'MICOSIS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '24', 'patologia' => 'HELMINTIASIS INTESTINALES MIXTAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '25', 'patologia' => 'PARASITOSIS INTESTINAL', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '26', 'patologia' => 'TUMORES MALIGNOS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '27', 'patologia' => 'TUMORES BENIGNOS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '28', 'patologia' => 'CANCER IN SENF. APARATO GENITOURINARIO', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '29', 'patologia' => 'BOCIO', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '30', 'patologia' => 'DIABETES', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '31', 'patologia' => 'ANEMIAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '36', 'patologia' => 'TRASTORNO DE LA INCLINACION SEXUAL', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '37', 'patologia' => 'SINDROME DEPENDENCIA DEL ALCOHOL', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '38', 'patologia' => 'SINDROME DE DEPENDENCIA CON CONSUMO ACTUAL DE LA SUSTANCIA', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '39', 'patologia' => 'INTOX.AGUDA NO COMPLICADA', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '43', 'patologia' => 'SINDROME HIPERSINETICO DE LA NIÑEZ', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '46', 'patologia' => 'EPILEPSIA', 'secundario' => 'G40-G40.9', 'categoria' => 'SM1'],
            ['codigo' => '47', 'patologia' => 'NEUMONIAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '48', 'patologia' => 'FARINGOAMIGDALITIS ESTREPTOCOCICAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '49', 'patologia' => 'ASMA BRONQUIAL', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '50', 'patologia' => 'FARINGOAMIGDALITIS VIRAL', 'secundario' => '', 'categoria' => 'IRA'],
            ['codigo' => '51', 'patologia' => 'FARINGITIS', 'secundario' => '', 'categoria' => 'IRA'],
            ['codigo' => '52', 'patologia' => 'RESFRIO COMUN', 'secundario' => '', 'categoria' => 'IRA'],
            ['codigo' => '53', 'patologia' => 'ENF. APARATO GENITOURINARIO', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '54', 'patologia' => 'FIEBRE REUMATICA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '55', 'patologia' => 'HIPERTENSION ARTERIAL', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '56', 'patologia' => 'CARDIOPATIAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '57', 'patologia' => 'ENFERMEDAD CEREBRO VASCULAR', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '58', 'patologia' => 'STRESS FISICO', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '59', 'patologia' => 'HERNIAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '60', 'patologia' => 'DISLIPIDEMIA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '61', 'patologia' => 'CERVICITIS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '62', 'patologia' => 'PROLAPSO GENITAL', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '63', 'patologia' => 'COMPLICACIONES DEL EMBARAZO', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '64', 'patologia' => 'DERMATITIS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '65', 'patologia' => 'FRACTURAS Y CONTUSIONES', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '66', 'patologia' => 'LESIONES, ENVENENAMIENTO: SUICIDIOS Y LESIONES INTENCIONALMENTE AUTOINFLINGIDAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '67', 'patologia' => 'ALERGIAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '68', 'patologia' => 'MORDEDURAS ANIMALES TRASM DE RABIA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '69', 'patologia' => 'DESNUTRICION', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '70', 'patologia' => 'CONJUNTIVITIS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '71', 'patologia' => 'OTITIS MEDIA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '72', 'patologia' => 'VARICELA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '73', 'patologia' => 'GASTRITIS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '74', 'patologia' => 'HERIDAS Y TRAUMATISMOS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '76', 'patologia' => 'PROBLEMAS RELACIONADOS CON EL USO DEL ALCOHOL', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '77', 'patologia' => 'PROBLEMAS RELACIONADOS CON EL USO DE LAS DROGAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '80', 'patologia' => 'FIBROMIALGIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '82', 'patologia' => 'PTERIGION', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '83', 'patologia' => 'ULCERAS VARICOSAS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '84', 'patologia' => 'OSTEOCONDRITIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '85', 'patologia' => 'HIPERCOLESTEROLEMIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '86', 'patologia' => 'HIPERTRIGLICEROLEMIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '87', 'patologia' => 'TORTICOLIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '88', 'patologia' => 'ESTRESS FISICO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '89', 'patologia' => 'OVARIOS POLIQUISTICOS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '90', 'patologia' => 'ERGE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '91', 'patologia' => 'SINDROME BRONQUIAL OBSTRUCTIVO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '93', 'patologia' => 'PEDICULOSIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '94', 'patologia' => 'PSORIASIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '95', 'patologia' => 'INSUFICIENCIA VENOSA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '96', 'patologia' => 'DORSALGIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '97', 'patologia' => 'EPOC', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '98', 'patologia' => 'OBESIDAD', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '99', 'patologia' => 'CARIES DENTAL', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '100', 'patologia' => 'MIASIS CUTANEA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '101', 'patologia' => 'PITIRIASIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '102', 'patologia' => 'OTRAS PATOLOGIAS', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '103', 'patologia' => 'SINTOMATICO RESPIRATORIO', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '104', 'patologia' => 'ATENCION PRENATAL ANTES DE LAS 12 SG', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '105', 'patologia' => 'ATENCION PRENATAL DESPUES DE LAS 12 SG', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '106', 'patologia' => 'ATENCION PRENATAL EDAD GESTACIONAL NO CONSIGNADA', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '107', 'patologia' => 'CITOLOGIA A EMBARAZADA', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '108', 'patologia' => 'CITOLOGIA A PACIENTE NO EMBARAZADA', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '109', 'patologia' => 'COLPOSCOPÍAS REALIZADAS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '110', 'patologia' => 'USG REALIZADOS A EMBARAZADAS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '111', 'patologia' => 'USG REALIZADOS A OTROS PACIENTES', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '112', 'patologia' => 'PARTOS ATENDIDOS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '113', 'patologia' => 'AMEU REALIZADAS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '114', 'patologia' => 'ATENCIÓN PUERPERAL EN LOS PRIMEROS 10 DÍAS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '115', 'patologia' => 'ATENCIÓN PUERPERAL ENTRE LOS 11 Y 40 DIAS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '116', 'patologia' => 'ANTICONCEPTIVO ORAL 1 CICLO', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '117', 'patologia' => 'ANTICONCEPTIVO ORAL 3 CICLO', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '118', 'patologia' => 'ANTICONCEPTIVO ORAL 6 CICLO', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '119', 'patologia' => 'CONDONES 10 UNIDADES', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '120', 'patologia' => 'CONDONES 30 UNIDADES', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '121', 'patologia' => 'DEPO PROVERAS APLICADAS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '122', 'patologia' => 'DIU INSERTADOS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '123', 'patologia' => 'NO.USUARIAS UILIZANDO EL METODO DE DIAS FIJOS (COLLAR)', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '124', 'patologia' => 'AQV REALIZADOS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '125', 'patologia' => 'VASECTORMÍAS REALIZADAS', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '126', 'patologia' => 'IMPLANTE SUB DERMICO', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '127', 'patologia' => 'REHIDRATACION ORAL', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '128', 'patologia' => 'CRECIMIENTO INADECUADO', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '129', 'patologia' => 'OTRAS ACTIVIDADES EN PLANIFICACION FAMILIAR', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '130', 'patologia' => 'ATENCION CLINICA POR COVID-19', 'secundario' => '', 'categoria' => 'AT2-R'],
            ['codigo' => '131', 'patologia' => 'ENTREVISTA PSICOLÓGICA', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '132', 'patologia' => 'INTERVENSIÓN EN CRISIS', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '133', 'patologia' => 'FICHA DE VIGILANCIA EPIDEMIOLÓGICA.', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '134', 'patologia' => 'PSICOTERAPIA INDIVIDUAL', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '135', 'patologia' => 'PSICOTERAPIA EN GRUPO', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '136', 'patologia' => 'NÚMERO DE PARTICIPANTES', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '137', 'patologia' => 'PSICOTERAPIA DE FAMILIA', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '138', 'patologia' => 'NÚMERO DE PARTICIPANTES', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '139', 'patologia' => 'REUNIÓN COORDINACIÓN GRUPOS DE APOYO', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '140', 'patologia' => 'NÚMERO DE PARTICIPANTES', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '141', 'patologia' => 'PRUEBAS PSICOLÓGICAS APLICADAS', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '142', 'patologia' => 'REUNIÓN DE TRABAJO COMUNITARIO', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '143', 'patologia' => 'NÚMERO DE PARTICIPANTES', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '144', 'patologia' => 'CAPACITACIONES BRINDADAS', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '145', 'patologia' => 'NÚMERO DE PARTICIPANTES', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '146', 'patologia' => 'CAPACITACIONES RECIBIDAS', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '147', 'patologia' => 'CHARLAS BRINDADAS', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '148', 'patologia' => 'NÚMERO DE PARTICIPANTES', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '149', 'patologia' => 'ORGANIZACIÓN Y FORTALECIMIENTO DE GRUPO', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '150', 'patologia' => 'CONSEJERIA VIH/SIDA', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '151', 'patologia' => 'REFERENCIAS RECIBIDAS', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '152', 'patologia' => 'REFERENCIAS ENVIADAS', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '153', 'patologia' => 'TAMIZAJE (+)', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '154', 'patologia' => 'TAMIZAJE  (-)', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '155', 'patologia' => 'TRAST. MENTALES INCLUIDOS LOS SINTOMATICOS (DEMENCIAS)', 'secundario' => 'F00-F09', 'categoria' => 'SM1'],
            ['codigo' => '156', 'patologia' => 'TRAST. MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL CONSUMO DE SUSTANCIAS PSICOTROPAS.', 'secundario' => 'F10-F19', 'categoria' => 'SM1'],
            ['codigo' => '157', 'patologia' => 'ESQUIZOFRENIA, TRANSTORNO ESQUIZOTIPICO Y TRANSTORNO DE IDEAS DELIRANTES.', 'secundario' => 'F20-F29', 'categoria' => 'SM1'],
            ['codigo' => '158', 'patologia' => 'TRANSTORNO DEL HUMOR (EPISODIO MANIACO)', 'secundario' => 'F30-F30.9', 'categoria' => 'SM1'],
            ['codigo' => '159', 'patologia' => 'TRANSTORNO DEL HUMOR (BIPOLAR)', 'secundario' => 'F31-F31.9', 'categoria' => 'SM1'],
            ['codigo' => '160', 'patologia' => 'TRANSTORNO DEL HUMOR EPISODIO DEPRESIVO', 'secundario' => 'F32-F39', 'categoria' => 'SM1'],
            ['codigo' => '161', 'patologia' => 'TRANSTORNOS NEUROTICOS, SECUNDARIOS A SITUACIONES ESTRESANTES SOMATOMORFOS.', 'secundario' => 'F40-F49', 'categoria' => 'SM1'],
            ['codigo' => '162', 'patologia' => 'TRANSTORNOS DEL COMPORTAMIENTO ASOCIADOS A DIFUNCIONES FISIOLOGICAS Y A FACTORES SOMÁTICOS.', 'secundario' => 'F50-F59', 'categoria' => 'SM1'],
            ['codigo' => '163', 'patologia' => 'TRANSTORNO DE LA PERSONALIDAD Y DEL COMPORTAMIENTO DEL ADULTO.', 'secundario' => 'F60-F69', 'categoria' => 'SM1'],
            ['codigo' => '164', 'patologia' => 'RETRASO MENTAL.', 'secundario' => 'F70-F79', 'categoria' => 'SM1'],
            ['codigo' => '165', 'patologia' => 'TRANSTORNO DEL DESARROLLO PSICOLÓGICO.', 'secundario' => 'F80-F89', 'categoria' => 'SM1'],
            ['codigo' => '166', 'patologia' => 'TRANSTORNOS DEL COMPORTAMIENTO Y DE LAS EMOCIONES DE COMIENZO HABITUAL EN LA INFANCIA Y LA ADOLECENCIA.', 'secundario' => 'F90-F98', 'categoria' => 'SM1'],
            ['codigo' => '167', 'patologia' => 'TRANSTORNO MENTAL SIN ESPECIFICACIONES', 'secundario' => 'F99', 'categoria' => 'SM1'],
            ['codigo' => '168', 'patologia' => 'ESTADO DE MAL EPILECTICO (STATUS) GRAN MAL Y PEQUEÑO MAL, PARCIAL, COMPLEJO, OTROS, DE TIPO NO ESPECIFICADO.', 'secundario' => 'G41-G41.9', 'categoria' => 'SM1'],
            ['codigo' => '169', 'patologia' => 'ENVENENAMIENTO O LESIÓN INTERNACIONALMENTE AUTOINFLINGIDA, INTENTO DE SUICIDIO POR DIFERENTES MEDIOS.', 'secundario' => 'X60-X69', 'categoria' => 'SM1'],
            ['codigo' => '170', 'patologia' => 'SUICIDIO Y LESIÓN INTERNACIONALMENTE AUTOINFLINGIDA POR DIFERENTES MEDIOS.', 'secundario' => 'X70-X84', 'categoria' => 'SM1'],
            ['codigo' => '171', 'patologia' => 'AGRESIONES, LESIONES OCASIONADAS POR OTRA PERSONA CON INTENTO DE LESIONES O MATAR POR CUALQUIER MEDIO (INCLUYE INTENTO DE HOMICIDIO, HOMICIDIO)', 'secundario' => 'X85-X99', 'categoria' => 'SM1'],
            ['codigo' => '172', 'patologia' => 'AGRESIÓN CON OBJETO ROMO O SIN FILO, POR EMPUJÓN ATROPELLO DELIBERADO CON VEHICULO DE MOTOR (INCLUYE INTENTO DE HOMICIDIO, HOMICIDIO)', 'secundario' => 'Y00-Y03', 'categoria' => 'SM1'],
            ['codigo' => '173', 'patologia' => 'AGRESIÓN CON FUERZA CORPORAL (INCLUYE LUCHAS O PELEAS SIN ARMAS , HOMICIDIO)', 'secundario' => 'Y04', 'categoria' => 'SM1'],
            ['codigo' => '174', 'patologia' => 'AGRESIÓN SEXUAL CON FUERZA CORPORAL (INCLUYE LUCHAS O PELEAS SIN ARMAS , HOMICIDIO)', 'secundario' => 'Y05', 'categoria' => 'SM1'],
            ['codigo' => '175', 'patologia' => '(VIOLACIÓN) INTIMIDACIÓN O ENGAÑO', 'secundario' => 'AA 206', 'categoria' => 'SM1'],
            ['codigo' => '176', 'patologia' => 'NEGLIGENCIA Y ABANDONO.', 'secundario' => 'Y06', 'categoria' => 'SM1'],
            ['codigo' => '177', 'patologia' => 'OTROS SINDROMES DE MALTRATO (CRUELDAD MENTAL, ABUSO FISICO, ABUSO SEXUAL Y TORTURA)', 'secundario' => 'Y07', 'categoria' => 'SM1'],
            ['codigo' => '178', 'patologia' => 'AGRESIÓN POR OTROS MEDIOS ESPECIFICADOS.', 'secundario' => 'Y08', 'categoria' => 'SM1'],
            ['codigo' => '179', 'patologia' => 'AGRESIÓN POR MEDIOS NO ESPECIFICADOS.', 'secundario' => 'Y09', 'categoria' => 'SM1'],
            ['codigo' => '180', 'patologia' => 'ABUSO FÍSICO', 'secundario' => 'T74.1', 'categoria' => 'SM1'],
            ['codigo' => '181', 'patologia' => 'ABUSO SEXUAL', 'secundario' => 'T74.2', 'categoria' => 'SM1'],
            ['codigo' => '182', 'patologia' => 'ABUSO PSICOLÓGICO', 'secundario' => 'T74.3', 'categoria' => 'SM1'],
            ['codigo' => '183', 'patologia' => 'VIOLENCIA FÍSICA', 'secundario' => 'AA 207', 'categoria' => 'SM1'],
            ['codigo' => '184', 'patologia' => 'VIOLENCIA SEXUAL', 'secundario' => 'AA 208', 'categoria' => 'SM1'],
            ['codigo' => '185', 'patologia' => 'VIOLENCIA PSICOLÓGICA.', 'secundario' => 'AA 175', 'categoria' => 'SM1'],
            ['codigo' => '186', 'patologia' => 'VIOLENCIA PATRIMONIAL / ECONÓMICA.', 'secundario' => 'AA 210', 'categoria' => 'SM1'],
            ['codigo' => '189', 'patologia' => 'SOSP. CHIKUNGUNYA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '190', 'patologia' => 'SECRECION URETRAL', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '192', 'patologia' => 'VAGINITIS', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '193', 'patologia' => 'ULCERA GENITAL', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '194', 'patologia' => 'EPI', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '195', 'patologia' => 'BUBON INGUINAL', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '196', 'patologia' => 'MOLUSCO CONTAGIOSO', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '197', 'patologia' => 'GRANULOMA INGUINAL', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '198', 'patologia' => 'CONDILOMA ACUMINADO', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '199', 'patologia' => 'VAGINOSIS BACTERIANA', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '200', 'patologia' => 'SIFILIS CONGENITA', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '202', 'patologia' => 'CLAMYDIA TRACHOMATIS', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '203', 'patologia' => 'TRICHOMONAS', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '204', 'patologia' => 'CANDIDA ALBICANS', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '206', 'patologia' => 'HERPES GENITAL', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '207', 'patologia' => 'HEPATITIS B', 'secundario' => '', 'categoria' => 'ITS'],
            ['codigo' => '208', 'patologia' => 'FEBRIL', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '209', 'patologia' => 'RH -', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '210', 'patologia' => 'CONTACTO TB', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '211', 'patologia' => 'REFERENCIA PSA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '212', 'patologia' => 'AQV', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '214', 'patologia' => 'SBO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '215', 'patologia' => 'condion femenino 1 unidad', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '216', 'patologia' => 'condon femenino 5 unidades', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '217', 'patologia' => 'REVISION IMPLANON', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '218', 'patologia' => 'RETIRO IMPLANON', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '219', 'patologia' => 'NIC 1', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '220', 'patologia' => 'sospecha de cancer', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '221', 'patologia' => 'TOMA DE PRESION', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '222', 'patologia' => 'ESCUELA SALUDABLE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '223', 'patologia' => 'DAÑO NUTRICIONAL GRAVE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '224', 'patologia' => 'EVALUACION NUTRICIONAL', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '225', 'patologia' => 'VIH POSITIVO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '227', 'patologia' => 'PREECLAMPSIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '228', 'patologia' => 'GLUCOMETRIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '229', 'patologia' => 'VPH AUTOTOMA CIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '230', 'patologia' => 'SINDROME CONGENITO ZIKA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '231', 'patologia' => 'DESCARTAR DIAGNOSTICO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '232', 'patologia' => 'NIÑO SANO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '233', 'patologia' => 'ADULTO SANO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '234', 'patologia' => 'OTRAS ACTIVIDADES DE PLANIFICACION FAMILIAR', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '235', 'patologia' => 'NIC 2', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '237', 'patologia' => 'CITA 3 AÑOS POST CRIOTERAPIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '238', 'patologia' => 'SINDROME CONVULSIVO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '239', 'patologia' => 'EXAMEN DE MAMAS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '240', 'patologia' => 'DIARREAS CON DESHIDRATACION', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '241', 'patologia' => 'CONSEJERIA PF/EMB/ZIKA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '242', 'patologia' => 'SOSPECHOSO COVID 19', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '243', 'patologia' => 'CONTACTO COVID-19', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '244', 'patologia' => 'REVI SOSP COVI CAMPO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '245', 'patologia' => 'IVAA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '246', 'patologia' => 'IVAA POSITIVA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '247', 'patologia' => 'IVAA NEGATIVA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '248', 'patologia' => 'IVAA (SOSP. CCU)', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '249', 'patologia' => 'CITOLOGIA POSITIVA CON IVAA NEGATIVA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '250', 'patologia' => 'VPH POR PROVEEDOR DE SALUD', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '251', 'patologia' => 'VPH POR AUTOTOMA EN ESTABLECIMIENTO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '252', 'patologia' => 'VPH POR AUTOTOMA EN COMUNIDAD', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '253', 'patologia' => 'VPH POSITIVO POR PROVEEDOR DE SALUD', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '254', 'patologia' => 'VPH POSITIVO POR AUTOTOMA EN ESTABLECIMIENTO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '255', 'patologia' => 'VPH POSITIVO POR AUTOTOMA EN COMUNIDAD', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '256', 'patologia' => 'VPH NEGATIVO POR PROVEEDOR DE SALUD', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '257', 'patologia' => 'VPH NEGATIVO POR AUTOTOMA EN ESTABLECIMIENTO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '258', 'patologia' => 'VPH NEGATIVO POR AUTOTOMA EN COMUNIDAD', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '259', 'patologia' => 'IVAA POSITIVA POR VPH POSITIVO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '260', 'patologia' => 'IVAA NEGATIVA POR VPH POSITIVO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '261', 'patologia' => 'CRIOTERAPIA POR CITOLOGIA (NICI/IVAA+)', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '262', 'patologia' => 'CRIOTERAPIA POR IVAA +', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '263', 'patologia' => 'CRIOTERAPIA POR VPH+/IVAA+', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '264', 'patologia' => 'CITA POST- CRIOTERAPIA AL MES', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '265', 'patologia' => 'REFERENCIA PARA REALIZAR IVAA POR VPH+', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '266', 'patologia' => 'REFERENCIA POR SOSPECHA DE CCU', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '267', 'patologia' => 'REFERENCIA COLPOSCOPIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '268', 'patologia' => 'REFERENCIA NO APLICA PARA CRIOTERAPIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '269', 'patologia' => 'REFERENCIA PARA CRIOTERAPIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '270', 'patologia' => 'REFERENCIA POR OTRO MOTIVO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '271', 'patologia' => 'REFERENCIA OTRO MOTIVO (IVAA/VPH)', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '272', 'patologia' => 'CONSEJERIA PREVIA REALIZACION DE TAMIZAJE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '273', 'patologia' => 'CONSEJERIA A LA PRUEBA DE RESULTADO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '274', 'patologia' => 'CONSEJERIA PREVIA A CRIOTERAPIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '275', 'patologia' => 'IVAA DUDOSA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '276', 'patologia' => 'CONTROL AL MES POST- CRIOTERAPIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '277', 'patologia' => 'IVAA POS- AÑO POST-CRIO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '278', 'patologia' => 'IVAA NEG- AÑO POST-CRIO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '279', 'patologia' => 'TERMO COAGULACION', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '280', 'patologia' => 'cita al mes pos termo coogulacion', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '281', 'patologia' => 'FALLECIDO COVID', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '282', 'patologia' => 'RINITIS ALERGICA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '283', 'patologia' => 'COLON IRRITABLE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '284', 'patologia' => 'BRONQUITIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '285', 'patologia' => 'HIPEREACTIVIDAD BRONQUIAL HRB', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '286', 'patologia' => 'ESCABIOSIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '287', 'patologia' => 'COVID RECUPERADO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '288', 'patologia' => 'SINOSITIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '289', 'patologia' => 'SECRECION VAGINAL', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '290', 'patologia' => 'TAMIZAJE COVID-19', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '291', 'patologia' => 'DESPARASITACION', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '292', 'patologia' => 'SECUELAS COVID', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '293', 'patologia' => 'PARATODITIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '296', 'patologia' => 'ULCERAS GASTRICAS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '297', 'patologia' => 'VIH-SIDA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '298', 'patologia' => 'ARTRITIS REUMATOIDE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '299', 'patologia' => 'SANGRADO TRANS VAGINAL', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '301', 'patologia' => 'DIARREAS SIN SANGRE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '302', 'patologia' => 'PARALISIS FLACIDA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '303', 'patologia' => 'SOSPECHOSO SARAMPION', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '304', 'patologia' => 'SOSPECHOSO TOSFERINA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '305', 'patologia' => 'TETANO', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '306', 'patologia' => 'PAROTIDITIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '307', 'patologia' => 'SOSPECHOSO RUBEOLA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '308', 'patologia' => 'SINDORME CONGENITO DE RUBEOLA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '310', 'patologia' => 'DENGUE', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '311', 'patologia' => 'EMBARAZADA ADOLESCENTE', 'secundario' => '', 'categoria' => 'EMB/ADOLES'],
            ['codigo' => '315', 'patologia' => 'MUJERES EMBARAZADAS SOSP. POR ZIKA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '316', 'patologia' => 'SOSP. GUILLIAN BARRé > 15 AÑOS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '317', 'patologia' => 'RABIA HUMANA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '318', 'patologia' => 'PESTE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '319', 'patologia' => 'FIEBRE AMARILLA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '320', 'patologia' => 'LEPTOSPIROSIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '321', 'patologia' => 'INTOXICACION POR PLAGUICIDAS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '322', 'patologia' => 'MORDEDURAS DE SERPIENTE', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '323', 'patologia' => 'MORTALIDAD INFANTIL (MENOR DE 1 AÑO)', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '324', 'patologia' => 'MORTALIDAD INFANTIL (1 - 4 AÑOS)', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '326', 'patologia' => 'MORTALIDAD MATERNA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '330', 'patologia' => 'SOSPECHA DENGUE SIN SIGNOS DE ALARMA', 'secundario' => '', 'categoria' => 'DENGUE'],
            ['codigo' => '331', 'patologia' => 'SOSPECHA DENGUE CON SIGNOS DE ALARMA', 'secundario' => '', 'categoria' => 'DENGUE'],
            ['codigo' => '332', 'patologia' => 'SOSPECHOSO DENGUE GRAVE', 'secundario' => '', 'categoria' => 'DENGUE'],
            ['codigo' => '333', 'patologia' => 'SOSPECHOSO CHICUNGUNYA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '334', 'patologia' => 'SOSP. ZIKA', 'secundario' => '', 'categoria' => 'MORBILIDAD'],
            ['codigo' => '335', 'patologia' => 'MENINGITIS', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '336', 'patologia' => 'ENTREVISTA V.D', 'secundario' => '', 'categoria' => 'SM1'],
            ['codigo' => '340', 'patologia' => 'BRONQUIOCTESIA', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '341', 'patologia' => 'INMUNIZACION', 'secundario' => '', 'categoria' => ''],
            ['codigo' => '401', 'patologia' => 'TRAST. MENTALES ORGÁNICOS INCLUIDOS LOS TRASTORNOS SINTOMÁTICOS (DEMENCIAS)', 'secundario' => 'F00-F09', 'auxiliar' => 'F00-F09', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '402', 'patologia' => 'TRASTORNOS MENTALES Y DEL COMPORTAMIENTO DEBIDOS AL CONSUMO DE SUSTANCIAS PSICOTROPAS', 'secundario' => 'F10-F19', 'auxiliar' => 'F10-F19', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '403', 'patologia' => 'ESQUIZOFRENIA, TRASTORNO ESQUIZOTIPICO Y TRASTORNO DE IDEAS DELIRANTES', 'secundario' => 'F20-F29', 'auxiliar' => 'F20-F29', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '404', 'patologia' => 'TRANSTORNOS DEL HUMOR (EPISODIO MANIACO)', 'secundario' => 'F30-F30.9', 'auxiliar' => 'F30-F30.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '405', 'patologia' => 'TASTORNOS DEL HUMOR AFECTIVO ( BIPOLAR)', 'secundario' => 'F31-F31.9', 'auxiliar' => 'F31-F31.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '406', 'patologia' => 'TRASTORNOS DEL HUMOR, EPISODIO DEPRESIVO', 'secundario' => 'F32-F32.9', 'auxiliar' => 'F32-F32.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '407', 'patologia' => 'TRASTORNO DEPRESIVO RECURRENTE, TRASTORNO SEL HUMOR (AFECTIVOS RECURREBTES),OTROS TRASTORNOS DE HUMOR AFECTIVOS OR ESPECIFICADOS.', 'secundario' => 'F33-F39.9', 'auxiliar' => 'F33-F39.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '408', 'patologia' => 'TRASTORNOS NEURÓTICOS, TRASTORNOS RELACIONADOS CON EL ESTRÉS Y TRASTORNOS SOMATOMORFOS', 'secundario' => 'F40-F48.9', 'auxiliar' => 'F40-F48.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '409', 'patologia' => 'SINDROME DEL COMPORTAMIENTO ASOCIADOS CON ALTERACIONES FISIOLOGICAS Y FACTORES FISICOS', 'secundario' => 'F50-F59.9', 'auxiliar' => 'F50-F59.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '410', 'patologia' => 'TRASTORNOS DE LA PERSONALIDAD Y DEL COMPORTAMIENTO DEL ADULTO', 'secundario' => 'F60-F69.9', 'auxiliar' => 'F60-F69.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '411', 'patologia' => 'RETRASO MENTAL', 'secundario' => 'F70-F79.9', 'auxiliar' => 'F70-F79.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '412', 'patologia' => 'TRASTORNOS DEL DESARROLLO PSICOLÓGICO', 'secundario' => 'F80-F89.9', 'auxiliar' => 'F80-F89.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '413', 'patologia' => 'TRASTORNO EMOCIONALES Y DEL COMPORTAMIENTO QUE APARECEN HABITUALMENTE EN LA NIÑEZ Y LA ADOLESCENCIA.', 'secundario' => 'F90-F98.9', 'auxiliar' => 'F90-F98.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '414', 'patologia' => 'TRASTORNO MENTAL SIN ESPECIFICACIÓN', 'secundario' => 'F99-F99.9', 'auxiliar' => 'F99-F99.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '415', 'patologia' => 'EPILEPSIA', 'secundario' => 'G40-G40.9', 'auxiliar' => 'G40-G40.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '416', 'patologia' => 'ESTADO DE MAL EPILÉPTICO (STATUS) GRAN MAL, Y PEQUEÑO MAL, PARCIAL, COMPLEJO, OTROS, DE TIPO NO ESPECIFICADO, Y SE AGREGA ENTRE PARENTESIS ESTATUS.', 'secundario' => 'G41-G41.9', 'auxiliar' => 'G41-G41.9', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '417', 'patologia' => 'OTROS SINTOMAS QUE INVOLUCRAN EL ESTADO EMOCIONAL IDEACION SUICIDA/TENDENCIA.ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICIÓN A SUSTANCIAS NOCIVAS (X40-X49)', 'secundario' => 'R45.8, X40-X49', 'auxiliar' => 'R45.8, X40-X49', 'categoria' => 'SM3-07 OBVERSO'],
            ['codigo' => '418', 'patologia' => 'ENVENENAMIENTO O LESIÓN INTENSIONAL- ENVENENAMIENTO ACCIDENTAL POR, Y EXPOSICIÓN A SUSTANCIAS NOCIVAS.', 'secundario' => 'X40-X49', 'auxiliar' => 'X40-X49', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '419', 'patologia' => 'LESIONES AUTOINFLIGIDAS INTENCIONALMENTE', 'secundario' => 'X60-X84', 'auxiliar' => 'X60-X84', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '420', 'patologia' => 'INTENTO DE SUICIDIO Y SUICIDIO Y LESIÓN INTENCIONALMENTE AUTO INFRINGIDA POR DIFERENTES MEDIOS.', 'secundario' => 'X70-X84', 'auxiliar' => 'X70-X84', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '421', 'patologia' => 'INCLUYE: HOMICIDIO. LESIONES OCASIONADAS POR OTRA PERSONA CON INTENTO DE LESIONAR O MATAR (INCLUYE HOMICIDIO)', 'secundario' => 'X85-Y09', 'auxiliar' => 'X85-Y09', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '422', 'patologia' => 'SINDROME DE MALTRATO POR ESPOSO O PAREJA (QUIEN EJERCE ABUSO FISICO, SEXUAL, CRUELDAD MENTAL Y TORTURA)', 'secundario' => 'Y07', 'auxiliar' => 'Y07', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '423', 'patologia' => 'NEGLIGENCIA O ABANDONO (NIÑOS Y NIÑAS)', 'secundario' => 'T74.0', 'auxiliar' => 'T74.0', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '424', 'patologia' => 'ABUSO FÍSICO', 'secundario' => 'T74.1', 'auxiliar' => 'T74.1', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '425', 'patologia' => 'ABUSO SEXUAL', 'secundario' => 'T74.2', 'auxiliar' => 'T74.2', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '426', 'patologia' => 'ABUSO PSICOLÓGICO', 'secundario' => 'T74.3', 'auxiliar' => 'T74.3', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '427', 'patologia' => 'VIOLENCIA FÍSICA', 'secundario' => 'AA 207', 'auxiliar' => 'AA 207', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '428', 'patologia' => 'VIOLENCIA SEXUAL', 'secundario' => 'AA 208', 'auxiliar' => 'AA 208', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '429', 'patologia' => 'VIOLENCIA PSICOLÓGICA', 'secundario' => 'AA 175', 'auxiliar' => 'AA 175', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '430', 'patologia' => 'VIOLENCIA PATRIMONIAL / ECONOMICA.', 'secundario' => 'AA 210', 'auxiliar' => 'AA 210', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '431', 'patologia' => 'CONTACTO CON Y EXPOSICIÓN A ENFERMEDADES TRANSMISIBLES (RELACIONADO A VIH, TB Y OTRAS TRANSMISIBLES )', 'secundario' => 'Z20', 'auxiliar' => 'Z20', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '432', 'patologia' => 'PERSONAS CON RIESGO POTENCIAL PARA SU SALUD RELACIONADO CON CIRCUNSTANCIAS SOCIOECONOMICAS Y PSICOSOCIALES', 'secundario' => 'Z55-Z65', 'auxiliar' => 'Z55-Z65', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '433', 'patologia' => 'OTROS PROBLEMAS RELACIONADOS CON EL GRUPO PRIMARIO DE APOYO', 'secundario' => 'Z63', 'auxiliar' => 'Z63', 'categoria' => 'SM3-07 REVERSO'],
            ['codigo' => '434', 'patologia' => 'CONSULTA RELACIONADA CON ACTITUD, CONDUCTA U ORIENTACION SEXUAL', 'secundario' => 'Z70', 'auxiliar' => 'Z70', 'categoria' => 'SM3-07 REVERSO']
        ];

        // Limpiar tabla primero para evitar duplicados
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Diagnostico::truncate();
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        foreach ($diagnosticos as $diagnostico) {
            Diagnostico::updateOrCreate(
            ['codigo' => $diagnostico['codigo'], 'patologia' => $diagnostico['patologia']],
                $diagnostico
            );
        }
    }
}