<?php

namespace Database\Seeders;

use App\Models\Medico;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MedicosSeeder extends Seeder
{
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Medico::truncate();
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $medicos = [
            [
                'COD_MED' => '1',
                'NOM_MED' => 'DRA. IVINS JANETH SAENZ',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 1, 1),
                'CORREO' => 'ivins.saenz@clinica.com',
                'TELEFONO' => '9999-9999',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '2',
                'NOM_MED' => 'DRA. LESLY AIDA CASTRO',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 1, 1),
                'CORREO' => 'lesly.castro@clinica.com',
                'TELEFONO' => '8888-8888',
                'HORAS_CONTRATADAS' => 36.50,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '3',
                'NOM_MED' => 'DR. ALFONSO ENRIQUE AUERBACH',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 5, 15),
                'CORREO' => 'alfonso.auerbach@clinica.com',
                'TELEFONO' => '7777-7777',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '4',
                'NOM_MED' => 'DR. GUSTAVO MANZANARES',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2018, 3, 10),
                'CORREO' => 'gustavo.manzanares@clinica.com',
                'TELEFONO' => '6666-6666',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '5',
                'NOM_MED' => 'DR. JOSE LEONEL GOMEZ',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 7, 22),
                'CORREO' => 'leonel.gomez@clinica.com',
                'TELEFONO' => '5555-5555',
                'HORAS_CONTRATADAS' => 38.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '6',
                'NOM_MED' => 'DRA. LINA ADRIANA SOSA',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 2, 14),
                'CORREO' => 'lina.sosa@clinica.com',
                'TELEFONO' => '4444-4444',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '7',
                'NOM_MED' => 'DR. TOMAS SANTOS',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 11, 5),
                'CORREO' => 'tomas.santos@clinica.com',
                'TELEFONO' => '3333-3333',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '8',
                'NOM_MED' => 'DRA. ALICIA ARZU',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 8, 19),
                'CORREO' => 'alicia.arzu@clinica.com',
                'TELEFONO' => '2222-2222',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '9',
                'NOM_MED' => 'DRA. KAREN LUCIA ARAGON',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 1, 10),
                'CORREO' => 'karen.aragon@clinica.com',
                'TELEFONO' => '1111-1111',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '10',
                'NOM_MED' => 'DRA. MIRIAN BARAHONA',
                'JORNADA' => 'FIN DE SEMANA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 6, 30),
                'CORREO' => 'mirian.barahona@clinica.com',
                'TELEFONO' => '0000-0000',
                'HORAS_CONTRATADAS' => 24.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '11',
                'NOM_MED' => 'G.O. DRA. ANA CARRILLO',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'ESPECIALISTA',
                'ESPECIALIDAD' => 'GINECOLOGIA',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2018, 4, 15),
                'CORREO' => 'ana.carrillo@clinica.com',
                'TELEFONO' => '9999-8888',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta ginecológica',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '12',
                'NOM_MED' => 'LICENCIADAS EN ENFERMERIA',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'LICENCIADAS EN ENFERMERIA',
                'ESPECIALIDAD' => 'LICENCIADAS EN ENFERMERIA',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 1, 1),
                'CORREO' => 'enfermeria@clinica.com',
                'TELEFONO' => '7777-6666',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Atención de enfermería',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '13',
                'NOM_MED' => 'ENFERMERAS AUXILIARES',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'ENFERMERAS AUXILIARES',
                'ESPECIALIDAD' => 'ENFERMERAS AUXILIARES',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 1, 1),
                'CORREO' => 'auxiliares@clinica.com',
                'TELEFONO' => '7777-5555',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Atención auxiliar',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '14',
                'NOM_MED' => 'DR. JAVIER ALMENDARES',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'ESPECIALISTA',
                'ESPECIALIDAD' => 'PEDIATRA',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2017, 8, 12),
                'CORREO' => 'javier.almendares@clinica.com',
                'TELEFONO' => '8888-7777',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta pediátrica',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '15',
                'NOM_MED' => 'CONSEJERIA',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'CONSEJERIA',
                'ESPECIALIDAD' => 'CONSEJERIA',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 3, 3),
                'CORREO' => 'consejeria@clinica.com',
                'TELEFONO' => '5555-4444',
                'HORAS_CONTRATADAS' => 30.00,
                'CONSULTAS' => 'Consejería médica',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '16',
                'NOM_MED' => 'DRA. YUSEN NUÑEZ',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 5, 18),
                'CORREO' => 'yusen.nunez@clinica.com',
                'TELEFONO' => '4444-3333',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '17',
                'NOM_MED' => 'DR. EDWIN JOSUE ESPINAL MARTINEZ',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 9, 1),
                'CORREO' => 'edwin.espinal@clinica.com',
                'TELEFONO' => '3333-2222',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '18',
                'NOM_MED' => 'DR. OSCAR RENE SALINAS ANDRADE',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 12, 15),
                'CORREO' => 'oscar.salinas@clinica.com',
                'TELEFONO' => '2222-1111',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '19',
                'NOM_MED' => 'DRA. DULCE SOFIA TORRES MORENO',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 3, 22),
                'CORREO' => 'dulce.torres@clinica.com',
                'TELEFONO' => '1111-0000',
                'HORAS_CONTRATADAS' => 38.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '20',
                'NOM_MED' => 'DR. LENIN ENRIQUE PACHECO',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 4, 7),
                'CORREO' => 'lenin.pacheco@clinica.com',
                'TELEFONO' => '9999-1111',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '21',
                'NOM_MED' => 'DRA. GABRIELA MARIA MONTESI',
                'JORNADA' => 'FIN DE SEMANA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 6, 11),
                'CORREO' => 'gabriela.montesi@clinica.com',
                'TELEFONO' => '8888-2222',
                'HORAS_CONTRATADAS' => 24.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '22',
                'NOM_MED' => 'DR. EDGAR FRANCISCO MOTIÑO',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 7, 19),
                'CORREO' => 'edgar.motino@clinica.com',
                'TELEFONO' => '7777-3333',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '23',
                'NOM_MED' => 'DR. BALTAZAR RODAS',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 2, 28),
                'CORREO' => 'baltazar.rodas@clinica.com',
                'TELEFONO' => '6666-4444',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '24',
                'NOM_MED' => 'DR. SERGEI GUZMAN',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 1, 5),
                'CORREO' => 'sergei.guzman@clinica.com',
                'TELEFONO' => '5555-6666',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '25',
                'NOM_MED' => 'DRA. MAGALY COELLO',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2018, 10, 15),
                'CORREO' => 'magaly.coello@clinica.com',
                'TELEFONO' => '4444-7777',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '26',
                'NOM_MED' => 'DRA. PATRICIA MARIA MEDINA',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 11, 30),
                'CORREO' => 'patricia.medina@clinica.com',
                'TELEFONO' => '3333-8888',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '27',
                'NOM_MED' => 'DR. CARLOS ALMENDAREZ',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 6, 24),
                'CORREO' => 'carlos.almendarez@clinica.com',
                'TELEFONO' => '2222-9999',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '28',
                'NOM_MED' => 'DR. LUIS ENRIQUE TRUNDLE',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 4, 12),
                'CORREO' => 'luis.trundle@clinica.com',
                'TELEFONO' => '1111-2222',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '29',
                'NOM_MED' => 'PSICOLOGIA',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'PSICOLOGIA',
                'ESPECIALIDAD' => 'PSICOLOGIA',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 5, 20),
                'CORREO' => 'psicologia@clinica.com',
                'TELEFONO' => '9999-3333',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta psicológica',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '30',
                'NOM_MED' => 'DR. JOSUE RICARDO VARELA',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'CONTRATO',
                'FECHA_INGRESO' => Carbon::create(2021, 7, 1),
                'CORREO' => 'josue.varela@clinica.com',
                'TELEFONO' => '8888-4444',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '31',
                'NOM_MED' => 'DRA. ANA SARAI FAJARDO VALLADARES',
                'JORNADA' => 'FIN DE SEMANA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 2, 28),
                'CORREO' => 'ana.fajardo@clinica.com',
                'TELEFONO' => '7777-9999',
                'HORAS_CONTRATADAS' => 24.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '32',
                'NOM_MED' => 'DR. FERNANDO FIGUEROA',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'ESPECIALISTA',
                'ESPECIALIDAD' => 'PSIQUIATRA',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2018, 9, 10),
                'CORREO' => 'fernando.figueroa@clinica.com',
                'TELEFONO' => '6666-8888',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta psiquiátrica',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '33',
                'NOM_MED' => 'DR. PEDRO ARIEL TROCHEZ MIRANDA',
                'JORNADA' => 'FIN DE SEMANA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 12, 15),
                'CORREO' => 'pedro.trochez@clinica.com',
                'TELEFONO' => '5555-9999',
                'HORAS_CONTRATADAS' => 24.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '34',
                'NOM_MED' => 'DR. JOSUE FERNARDO RODAS ANDINO',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 8, 22),
                'CORREO' => 'josue.rodas@clinica.com',
                'TELEFONO' => '4444-5555',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '35',
                'NOM_MED' => 'DR. RAMON FERNANDO YANEZ',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'PSIQUIATRA',
                'ESPECIALIDAD' => 'PSIQUIATRA',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2017, 11, 30),
                'CORREO' => 'ramon.yanez@clinica.com',
                'TELEFONO' => '3333-6666',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta psiquiátrica',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '36',
                'NOM_MED' => 'DRA. LESLY JANNETH VALLEJO',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 1, 15),
                'CORREO' => 'lesly.vallejo@clinica.com',
                'TELEFONO' => '2222-7777',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '37',
                'NOM_MED' => 'SARA BETSABETH FUNEZ',
                'JORNADA' => 'FIN DE SEMANA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'INTERINATO',
                'FECHA_INGRESO' => Carbon::create(2021, 9, 1),
                'CORREO' => 'sara.funez@clinica.com',
                'TELEFONO' => '1111-8888',
                'HORAS_CONTRATADAS' => 24.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '38',
                'NOM_MED' => 'MSS.NANCY STEFANIA ANDRADE',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 10, 10),
                'CORREO' => 'nancy.andrade@clinica.com',
                'TELEFONO' => '9999-5555',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '39',
                'NOM_MED' => 'MSS.LUIS FERNANDO MEJIA',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2019, 4, 18),
                'CORREO' => 'luis.mejia@clinica.com',
                'TELEFONO' => '8888-6666',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '40',
                'NOM_MED' => 'DR. WALTER EDGARDO CRUZ PERDOMO',
                'JORNADA' => 'VESPERTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2020, 3, 25),
                'CORREO' => 'walter.cruz@clinica.com',
                'TELEFONO' => '7777-0000',
                'HORAS_CONTRATADAS' => 36.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ],
            [
                'COD_MED' => '41',
                'NOM_MED' => 'DR.KENNETH RODRIGO MANZANARES',
                'JORNADA' => 'MATUTINA',
                'NOMINA' => 'MEDICO ASISTENCIAL',
                'ESPECIALIDAD' => 'MEDICO GENERAL',
                'MODALIDAD' => 'PERMANENTE',
                'FECHA_INGRESO' => Carbon::create(2021, 1, 1),
                'CORREO' => 'kenneth.manzanares@clinica.com',
                'TELEFONO' => '6666-9999',
                'HORAS_CONTRATADAS' => 40.00,
                'CONSULTAS' => 'Consulta general',
                'estado' => 'activo'
            ]
        ];

        // Insertar en chunks de 10
        collect($medicos)->chunk(10)->each(function ($chunk) {
            Medico::insert($chunk->toArray());
        });
    }
}